# Generated by Django 5.0 on 2023-12-24 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 18, 0, 32, 152978, tzinfo=datetime.timezone.utc)),
        ),
    ]
