# Generated by Django 5.0 on 2023-12-24 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 18, 13, 3, 325211, tzinfo=datetime.timezone.utc)),
        ),
    ]
